---
title: "FMG Stand Walk Summary Sheet"
output:
  pdf_document: default
  html_document:
    css: style_1.css
---

```{r get_data, echo=FALSE}
# collector
forester <- ""
date <- ""

# stand_id
pool        <- "Pool 13"
compartment <- "c0078"
unit        <- "U0124"
site        <- "T0987"
stand       <- "S0001"
num_plots      <- 25
num_age_plots  <- 5
walk_acres     <- 5.7
inventory_year <- 2011
dom_soil_type  <- "Grafton Silty Loam"

# stand-summary-data
tpa              <- 85
basal_area       <- 300
qm_dbh           <- 4.7
stocking         <- 55
canopy_height    <- 120
canopy_closure   <- 0.80
hard_mast_tpa    <- 15
hard_mast_ba     <- 37
hard_mast_qm_dbh <- 118
hard_mast_stock  <- 134
under_height     <- 22
snag_tpa         <- 2
stand_age        <- 72
hard_mast_age    <- 85
growth           <- 23
stand_health     <- 56
species_rich     <- 1.2
regen_rate       <- 33

# Size Class Distribution (TPA)
polesize   <- 45
sawtimber  <- 68
mature     <- 89
overmature <- 27

# Top 3 Understory Species
under_species_1 <- "FRMW"
under_species_2 <- "HTXR"
under_species_3 <- "DRPT"

# Top 3 Ground Species
ground_species_1 <- "AWQC"
ground_species_2 <- "KLOR"
ground_species_3 <- "NWPT"

# Top 5 Overstory Species
o1_usda_code  <- "ACGR"
o1_avg_tpa    <- 126
o1_avg_ba     <- 35
o1_qm_dbh     <- 14
o1_target_tpa <- 110
o1_target_ba  <- 19
o2_usda_code  <- "WSTR"
o2_avg_tpa    <- 126
o2_avg_ba     <- 35
o2_qm_dbh     <- 14
o2_target_tpa <- 110
o2_target_ba  <- 19
o3_usda_code  <- "FAPT"
o3_avg_tpa    <- 126
o3_avg_ba     <- 35
o3_qm_dbh     <- 14
o3_target_tpa <- 110
o3_target_ba  <- 19
o4_usda_code  <- "BRHT"
o4_avg_tpa    <- 126
o4_avg_ba     <- 35
o4_qm_dbh     <- 14
o4_target_tpa <- 110
o4_target_ba  <- 19
o5_usda_code  <- "QRRB"
o5_avg_tpa    <- 126
o5_avg_ba     <- 35
o5_qm_dbh     <- 14
o5_target_tpa <- 110
o5_target_ba  <- 19
```

<!--
## Stand ID
-->

::::: {#collector .grid-5w-1h }
::: {.var-name}
Forester
:::
::: {.empty-box}
`r forester`
:::
::: {.var-name}
Date
:::
::: {.empty-box}
`r date`
:::
:::::

::::: {#stand_id_1 .grid-5w-2h}
::: {.var-name}
Pool
:::
::: {.var-value}
`r pool`
:::
::: {.var-name}
Compartment
:::
::: {.var-value}
`r compartment`
:::
::: {.var-name}
Unit
:::
::: {.var-value}
`r unit`
:::
::: {.var-name}
Site 
:::
::: {.var-value}
`r site`
:::
::: {.var-name}
Stand 
:::
::: {.var-value}
`r stand`
:::
:::::

::::: {#stand_id_2 .grid-5w-2h}
::: {.var-name}
\# of Plots
:::
::: {.var-value}
`r num_plots`
:::
::: {.var-name}
\# Age Plots
:::
::: {.var-value}
`r num_age_plots`
:::
::: {.var-name}
Walk Acreage
:::
::: {.var-value}
`r walk_acres`
:::
::: {.var-name}
Inventory Year
:::
::: {.var-value}
`r inventory_year`
:::
::: {.var-name}
Dominant Soil Type
:::
::: {.var-value}
`r dom_soil_type`
:::
:::::



## Stand Summary Data

::::: {#stand-summary-data .grid-6w-6h}
::: {.var-name}
Trees per Acre
:::
::: {.var-value}
`r tpa`
:::
::: {.var-name}
Hard Mast TPA
:::
::: {.var-value}
`r hard_mast_tpa`
:::
::: {.var-name}
Stand Age
:::
::: {.var-value}
`r stand_age`
:::
::: {.var-name}
Basal Area
:::
::: {.var-value}
`r basal_area`
:::
::: {.var-name}
Hard Mast BA
:::
::: {.var-value}
`r hard_mast_ba`
:::
::: {.var-name}
Hard Mast Age
:::
::: {.var-value}
`r hard_mast_age`
:::
::: {.var-name}
QM DBH
:::
::: {.var-value}
`r qm_dbh`
:::
::: {.var-name}
Hard Mast QM DBH
:::
::: {.var-value}
`r hard_mast_qm_dbh`
:::
::: {.var-name}
Growth
:::
::: {.var-value}
`r growth`
:::
::: {.var-name}
Stocking
:::
::: {.var-value}
`r stocking`
:::
::: {.var-name}
Hard Mast Stocking
:::
::: {.var-value}
`r hard_mast_stock`
:::
::: {.var-name}
Stand Health
:::
::: {.var-value}
`r stand_health`
:::
::: {.var-name}
Canopy Height
:::
::: {.var-value}
`r canopy_height`
:::
::: {.var-name}
Understory Height
:::
::: {.var-value}
`r under_height`
:::
::: {.var-name}
Species Richness
:::
::: {.var-value}
`r species_rich`
:::
::: {.var-name}
Canopy Closure
::: 
::: {.var-value}
`r canopy_closure`
:::
::: {.var-name}
Snag TPA
:::
::: {.var-value}
`r snag_tpa`
:::
::: {.var-name}
Regeneration Rate
:::
::: {.var-value}
`r regen_rate`
:::
:::::


<!--
## Section 3
-->

:::::::::::: {#section-3 .group-3-horz}
:::::::: {.section-box}
### Size Class Distribution (TPA)

::::: {.grid-2w-4h}
::: {.var-name}
Polesize (8"-12")
:::
::: {.var-value}
`r polesize`
:::
::: {.var-name}
Sawtimber (12"-18")
:::
::: {.var-value}
`r sawtimber`
:::
::: {.var-name}
Mature (18"-24")
:::
::: {.var-value}
`r mature`
:::
::: {.var-name}
Overmature (24"+)
:::
::: {.var-value}
`r overmature`
:::
:::::
::::::::
:::::::: {.section-box}
### Top 3 Understory Species

::::: {.grid-2w-4h}
::: {.var-name}
Species 1
:::
::: {.var-value}
`r under_species_1`
:::
::: {.var-name}
Species 2
:::
::: {.var-value}
`r under_species_2`
:::
::: {.var-name}
Species 3
:::
::: {.var-value}
`r under_species_3`
:::
:::::
::::::::
:::::::: {.section-box}
### Top 3 Ground Species

::::: {.grid-2w-4h}
::: {.var-name}
Species 1
:::
::: {.var-value}
`r ground_species_1`
:::
::: {.var-name}
Species 2
:::
::: {.var-value}
`r ground_species_2`
:::
::: {.var-name}
Species 3
:::
::: {.var-value}
`r ground_species_3`
:::
:::::
::::::::
::::::::::::



<!--
## Section 4
-->

:::::::::::: {#section-4 .group-5-vert}
### Top 5 Overstory Species

<!-- Overstory Species 1 -->
:::::::: {.section-box}
::::: {.grid-6w-2h}
::: {.var-name}
USDA Code
:::
::: {.var-value}
`r o1_usda_code`
:::
::: {.var-name}
Avg. TPA
:::
::: {.var-value}
`r o1_avg_tpa`
:::
::: {.var-name}
Avg. BA
:::
::: {.var-value}
`r o1_avg_ba`
:::
::: {.var-name}
QM DBH
:::
::: {.var-value}
`r o1_qm_dbh`
:::
::: {.var-name}
Target TPA
:::
::: {.var-value}
`r o1_target_tpa`
:::
::: {.var-name}
Target BA
:::
::: {.var-value}
`r o1_target_ba`
:::
:::::
::::::::

<!-- Overstory Species 2 -->
:::::::: {.section-box}
::::: {.grid-6w-2h}
::: {.var-name}
USDA Code
:::
::: {.var-value}
`r o2_usda_code`
:::
::: {.var-name}
Avg. TPA
:::
::: {.var-value}
`r o2_avg_tpa`
:::
::: {.var-name}
Avg. BA
:::
::: {.var-value}
`r o2_avg_ba`
:::
::: {.var-name}
QM DBH
:::
::: {.var-value}
`r o2_qm_dbh`
:::
::: {.var-name}
Target TPA
:::
::: {.var-value}
`r o2_target_tpa`
:::
::: {.var-name}
Target BA
:::
::: {.var-value}
`r o2_target_ba`
:::
:::::
::::::::

<!-- Overstory Species 3 -->
:::::::: {.section-box}
::::: {.grid-6w-2h}
::: {.var-name}
USDA Code
:::
::: {.var-value}
`r o3_usda_code`
:::
::: {.var-name}
Avg. TPA
:::
::: {.var-value}
`r o3_avg_tpa`
:::
::: {.var-name}
Avg. BA
:::
::: {.var-value}
`r o3_avg_ba`
:::
::: {.var-name}
QM DBH
:::
::: {.var-value}
`r o3_qm_dbh`
:::
::: {.var-name}
Target TPA
:::
::: {.var-value}
`r o3_target_tpa`
:::
::: {.var-name}
Target BA
:::
::: {.var-value}
`r o3_target_ba`
:::
:::::
::::::::

<!-- Overstory Species 4 -->
:::::::: {.section-box}
::::: {.grid-6w-2h}
::: {.var-name}
USDA Code
:::
::: {.var-value}
`r o4_usda_code`
:::
::: {.var-name}
Avg. TPA
:::
::: {.var-value}
`r o4_avg_tpa`
:::
::: {.var-name}
Avg. BA
:::
::: {.var-value}
`r o4_avg_ba`
:::
::: {.var-name}
QM DBH
:::
::: {.var-value}
`r o4_qm_dbh`
:::
::: {.var-name}
Target TPA
:::
::: {.var-value}
`r o4_target_tpa`
:::
::: {.var-name}
Target BA
:::
::: {.var-value}
`r o4_target_ba`
:::
:::::
::::::::

<!-- Overstory Species 5 -->
:::::::: {.section-box}
::::: {.grid-6w-2h}
::: {.var-name}
USDA Code
:::
::: {.var-value}
`r o5_usda_code`
:::
::: {.var-name}
Avg. TPA
:::
::: {.var-value}
`r o5_avg_tpa`
:::
::: {.var-name}
Avg. BA
:::
::: {.var-value}
`r o5_avg_ba`
:::
::: {.var-name}
QM DBH
:::
::: {.var-value}
`r o5_qm_dbh`
:::
::: {.var-name}
Target TPA
:::
::: {.var-value}
`r o5_target_tpa`
:::
::: {.var-name}
Target BA
:::
::: {.var-value}
`r o5_target_ba`
:::
:::::
::::::::

::::::::::::


